import { Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import { PDF_COLORS, PDF_FONTS, PDF_SPACING } from "@/lib/pdf-theme";

interface ContentPageProps {
  reportId: string;
  children: React.ReactNode;
}

const styles = StyleSheet.create({
  page: {
    backgroundColor: PDF_COLORS.background,
    paddingTop: PDF_SPACING.pageMargin,
    paddingBottom: PDF_SPACING.footerHeight + PDF_SPACING.pageMargin,
    paddingHorizontal: PDF_SPACING.pageMargin,
    fontFamily: "Helvetica",
  },
  header: {
    position: "absolute",
    top: 16,
    left: PDF_SPACING.pageMargin,
    right: PDF_SPACING.pageMargin,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: PDF_COLORS.border,
  },
  headerText: {
    fontSize: PDF_FONTS.tiny,
    color: PDF_COLORS.textMuted,
    fontFamily: "Courier",
  },
  body: {
    flex: 1,
  },
  footer: {
    position: "absolute",
    bottom: 16,
    left: PDF_SPACING.pageMargin,
    right: PDF_SPACING.pageMargin,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 8,
    borderTopWidth: 0.5,
    borderTopColor: PDF_COLORS.border,
  },
  footerLeft: {
    fontSize: PDF_FONTS.tiny,
    color: PDF_COLORS.textMuted,
    fontFamily: "Courier",
  },
  footerCenter: {
    fontSize: PDF_FONTS.tiny,
    color: PDF_COLORS.textMuted,
  },
  footerRight: {
    fontSize: PDF_FONTS.tiny,
    color: PDF_COLORS.textMuted,
  },
});

export default function ContentPage({ reportId, children }: ContentPageProps) {
  return (
    <Page size="A4" style={styles.page}>
      <View style={styles.header} fixed>
        <Text style={styles.headerText}>{reportId}</Text>
        <Text
          style={styles.headerText}
          render={({ pageNumber }) => `Page ${pageNumber}`}
        />
      </View>
      <View style={styles.body}>{children}</View>
      <View style={styles.footer} fixed>
        <Text style={styles.footerLeft}>{reportId}</Text>
        <Text style={styles.footerCenter}>Generated by Deep Research Engine</Text>
        <Text
          style={styles.footerRight}
          render={({ pageNumber }) => `${pageNumber}`}
        />
      </View>
    </Page>
  );
}
